export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const LOGOUT = "LOGOUT";
export const AUTH_LOADING = "AUTH_LOADING";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
export const GET_PRODUCT = "GET_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const FILTER_PRODUCT = "FILTER_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const GET_OWNED_PRODUCTS = "GET_OWNED_PRODUCTS";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_PRODUCT_SELLER_NUMBER = "GET_PRODUCT_SELLER_NUMBER";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const CATEGORY_ERROR = "CATEGORY_ERROR";
export const CATEGORY_LOADING = "CATEGORY_LOADING";
